% Jacob Bakermans, February 2016
function params = fretPerMolDialog()
    thresholdDialog = dialog('name', 'Set thresholds', ...
                         'color', [0.95 0.95 0.95], ...
                         'units', 'pixels', ...
                         'CloseRequestFcn', @cancel, ...
                         'DefaultUIPanelBackGroundColor', [0.95 0.95 0.95], ...
                         'DefaultUIControlUnits', 'normalized');
    
    % initialize output
    params = cell(5,1);
    for (i = 1:5)
        params{i} = -1;
    end
    
    % element sizes (pixels)
    row_height = 18;
    edit_width = 100;
    label_width = 100;

    % vertical and horizontal padding (pixels)
    pad_width = 6;
    pad_height = 6;

    % setFitStartDialog height and width
    num_rows = 6;
    thresholdDialog_height = (num_rows+1) * row_height + (num_rows+2) * pad_height;
    thresholdDialog_width = 3 * pad_width + label_width + edit_width;

    % get normalized units
    rh = row_height / thresholdDialog_height;
    ew = edit_width / thresholdDialog_width;
    lw = label_width / thresholdDialog_width;

    ph = pad_height / thresholdDialog_height;
    pw = pad_width  /thresholdDialog_width;

    % window_pos = get(gcbo(), 'position');
    % thresholdDialog_pos(1) = min(1, window_pos(1) + round(0.5 * (window_pos(3) - thresholdDialog_height)));
    % thresholdDialog_pos(2) = min(1, window_pos(2) + round(0.5 * (window_pos(4) - thresholdDialog_width)));
    % thresholdDialog_pos(3) = thresholdDialog_height;
    % thresholdDialog_pos(4) = thresholdDialog_width;

    % adjust thresholdDialog size
    rect = get(thresholdDialog, 'position');
    set(thresholdDialog, 'position', [rect(1)-0.5*thresholdDialog_width rect(2)-0.5*thresholdDialog_height thresholdDialog_width thresholdDialog_height]);

    label.analysis ...
        = uicontrol(thresholdDialog, ...
            'style', 'text', ...
            'backgroundcolor', [0.95 0.95 0.95], ...
            'string', 'Leave empty to ignore', ...
            'horizontalalignment', 'center', ...
            'position', [pw 1-1*(rh+ph) 1-2*pw rh]);

    label.thres_1 ...
        = uicontrol(thresholdDialog, ...
            'style', 'text', ...
            'backgroundcolor', [0.95 0.95 0.95], ...
            'string', 'Threshold 1', ...
            'horizontalalignment', 'left', ...
            'position', [pw 1-2*(rh+ph) 1-2*ph rh]);          
        
    label.thres_2 ...
        = uicontrol(thresholdDialog, ...
            'style', 'text', ...
            'backgroundcolor', [0.95 0.95 0.95], ...
            'string', 'Threshold 2', ...
            'horizontalalignment', 'left', ...
            'position', [pw 1-3*(rh+ph) 1-2*pw rh]);        
        
    label.thres_3 ...
        = uicontrol(thresholdDialog, ...
            'style', 'text', ...
            'backgroundcolor', [0.95 0.95 0.95], ...
            'string', 'Threshold 3', ...
            'horizontalalignment', 'left', ...
            'position', [pw 1-4*(rh+ph) lw rh]);

    label.thres_4 ...
        = uicontrol(thresholdDialog, ...
            'style', 'text', ...
            'backgroundcolor', [0.95 0.95 0.95], ...
            'string', 'Threshold 4', ...
            'horizontalalignment', 'left', ...
            'position', [pw 1-5*(rh+ph) lw rh]);
        
    label.avg_frames ...
        = uicontrol(thresholdDialog, ...
            'style', 'text', ...
            'backgroundcolor', [0.95 0.95 0.95], ...
            'string', 'Frames to average', ...
            'horizontalalignment', 'left', ...
            'position', [pw 1-6*(rh+ph) lw rh]);        
    
    edit.thres_1 ...
        = uicontrol(thresholdDialog, ...
            'style', 'edit', ...
            'backgroundcolor', [0.95 0.95 0.95], ...            
            'string', '', ...
            'callback', @editValue, ...
            'position', [1-(pw+ew) 1-2*(rh+ph) ew rh]);       

    edit.thres_2 ...
        = uicontrol(thresholdDialog, ...
            'style', 'edit', ...
            'backgroundcolor', [0.95 0.95 0.95], ...            
            'string', '', ...
            'callback', @editValue, ...
            'position', [1-(pw+ew) 1-3*(rh+ph) ew rh]);        
        
    edit.thres_3 ...
        = uicontrol(thresholdDialog, ...
            'style', 'edit', ...
            'backgroundcolor', [0.95 0.95 0.95], ...            
            'string', '', ...
            'callback', @editValue, ...
            'position', [1-(pw+ew) 1-4*(rh+ph) ew rh]);

    edit.thres_4 ...
        = uicontrol(thresholdDialog, ...
            'style', 'edit', ...
            'backgroundcolor', [0.95 0.95 0.95], ...            
            'string', '', ...
            'callback', @editValue, ...
            'position', [1-(pw+ew) 1-5*(rh+ph) ew rh]);        
    edit.avg_frames ...
        = uicontrol(thresholdDialog, ...
            'style', 'edit', ...
            'backgroundcolor', [1 1 1], ...            
            'string', '1', ...
            'position', [1-(pw+ew) 1-6*(rh+ph) ew rh]);        
    
    okButton ...
        = uicontrol(thresholdDialog, ...
            'style', 'pushbutton', ...
            'string', 'Ok', ...
            'position', [pw ph 0.5-1.5*pw rh], ...
            'callback', @OK);
            % 'callback', ...
            %     @(source, event) return_values(1), ...
    cancelButton ...
        = uicontrol(thresholdDialog, ...
            'style', 'pushbutton', ...
            'string', 'Cancel', ...
            'position', [0.5+0.5*pw ph 0.5-1.5*pw rh], ...
            'callback', @cancel);        

    function editValue(source,callbackdata)
        if (isnan(str2double(get(source, 'string'))))
            set(source, 'backgroundcolor', [0.95 0.95 0.95]);
            set(source, 'string', '');
        else
            set(source, 'backgroundcolor', [1 1 1]);
        end
    end
        
    function OK(source,callbackdata)
        params{1} = str2double(get(edit.thres_1, 'string'));
        params{2} = str2double(get(edit.thres_2, 'string'));
        params{3} = str2double(get(edit.thres_3, 'string'));
        params{4} = str2double(get(edit.thres_4, 'string'));
        params{5} = str2double(get(edit.avg_frames, 'string'));                
        uiresume();
        delete(thresholdDialog);
    end

    function cancel(source,callbackdata)
        for (i = 1:5)
            params{i} = -1;
        end
        uiresume();
        delete(thresholdDialog);
    end

    uiwait(thresholdDialog);                    
end